hwdec=auto
vo=gpu
gpu-context=wayland
target-colorspace=bt.709
tone-mapping=clip
sub-font-size=28
audio-resample=yes
audio-resample-quality=high
audio-format=s32
audio-samplerate=48000
save-position-on-quit
resume-playback=yes
