# ------------------------
# Transparency
# ------------------------
background_opacity 0.55
dynamic_background_opacity yes
allow_remote_control yes
listen_on unix:@kitty

# ------------------------
# Core colors
# ------------------------
background #0b0f14
foreground #e7dcc5

cursor #f0c674
cursor_text_color #0b0f14

selection_background #3a2f1c
selection_foreground #f5e6c8

# ------------------------
# ANSI colors
# ------------------------
color0  #0b0f14
color1  #bf616a
color2  #7fa36b
color3  #f0c674
color4  #5f819d
color5  #b48ead
color6  #5e8d87
color7  #e7dcc5

color8  #3b4252
color9  #d08770
color10 #a3be8c
color11 #ffd479
color12 #81a1c1
color13 #c792ea
color14 #8fbcbb
color15 #f6ecd8

# ------------------------
# Font
# ------------------------
font_family SauceCodePro Nerd Font
font_size 10.5
disable_ligatures never
symbol_map U+1F300-U+1FAFF Noto Color Emoji

# Padding around terminal content
window_padding_width 14
window_padding_height 12

enable_graphics_protocol yes
term xterm-kitty
